### ISSUE TITLE
Optimal Batch Size

### ISSUE THREAD

**Issue by vinits5** [HighwayWu/ImageInpainting#3]
Hello,

Thank you for such a great job and for releasing your code.
I want to train your network using a custom dataset. When I looked at the options.py file, the batch_size parameter is set to 1 and has not changed anywhere in other training files. 
Do you find empirically that batch_size 1 works best with your network? Please suggest this parameter as my dataset contains almost 15000 images and it will be very slow to train with batch_size 1.
Thanks.

**Comment by HighwayWu** [comment]
Hi, Vinits.

I set the batch_size=1 mainly because of the limitation of resources. I think you could try a larger batch size according to your resources.
Sorry for the late reply.

Best,
Haiwei

**Comment by vinits5** [comment]
Sure. I will try other batch sizes.
