### ISSUE TITLE
How can I get the masked image during testing?

### ISSUE THREAD

**Issue by 01build** [HighwayWu/ImageInpainting#6]
![image](https://user-images.githubusercontent.com/59005451/122377088-55b70080-cf97-11eb-82c0-16b4a83ef863.png)
When I put the image and mask as the above picture's root,it just gives the inpainted result,but where should I get the masked image generated from the origin image and mask?

**Comment by HighwayWu** [comment]
Just use somethings like "img[mask==255]=255".
